name: cuacfm
description: A radio station with radioco integration.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
      sdk: flutter

  verbal_expressions: "^0.4.0"
  flutter_webview_plugin: "^0.3.10+1"
  audioplayers: "^0.14.0"
  intl: "^0.16.1"
  xml2json: "^4.1.1"
  cupertino_icons: "^0.1.3"
  device_info: "^0.4.1+5"
  http: "^0.12.0+4"
  html: ^0.14.0
  phonecallstate: ^1.0.1
  share: ^0.6.3+5
  shared_preferences: ^0.5.4+9
  injector: ^1.0.5
  animations: ^1.0.0+5
  flappy_search_bar: ^1.7.2
  cached_network_image: ^2.0.0
  flutter_html: ^0.11.0
  url_launcher: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
      - assets/graphics/icon_info.png
      - assets/graphics/play_podcast.png
      - assets/graphics/cuac-logo.png

  fonts:
      - family: Montserrat
        fonts:
          - asset: assets/fonts/Montserrat-Light.ttf