name: cuacfm
description: A new Flutter project.

dependencies:
  verbal_expressions: "^0.3.1"
  flutter_webview_plugin: "^0.0.9+1"
  audioplayer: "^0.3.0"
  xml2json: "^2.0.9"
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
      - family: Montserrat
        fonts:
          - asset: assets/fonts/Montserrat-Light.ttf



