name: cuacfm
description: A new Flutter project.

dependencies:
  verbal_expressions: "^0.3.1"
  flutter_webview_plugin: "^0.0.9+1"
  audioplayers: "^0.4.1"
  xml2json: "^2.0.9"
  intl: "^0.15.2"

  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
      - assets/graphics/icon_info.png
      - assets/graphics/play_podcast.png

  fonts:
      - family: Montserrat
        fonts:
          - asset: assets/fonts/Montserrat-Light.ttf



